version = 1

[[annotations]]
path = [
    "functions/.emulator-cache"
]
SPDX-FileCopyrightText = "2026 Stanford University and the project authors (see CONTRIBUTORS.md)"
SPDX-License-Identifier = "MIT"